name: event_creator
description: Event Creator app
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  dio: ^5.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  fluttertoast: ^8.2.2
  get_it: ^7.6.0
  go_router: ^7.1.1
  injectable: ^2.1.2
  intl: ^0.18.0
  shared_preferences: ^2.1.2
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.3.1
  injectable_generator: ^2.1.6
  lint: ^2.1.2

flutter_gen:
  output: lib/generated/

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
